# The values given here are actually the default values. But they are explicitly
# set here as an example of setting the Kafka properties.
spring:
  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: burgertopic
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
