spring:
  datasource:
    generate-unique-name: false
    name: burger
  data:
    rest:
      base-path: /data-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

#logging:
#  file:
#    name: TacoCloud.log
#  level:
#    root: INFO
#    org:
#      springframework:
#      security: DEBUG

burger:
  orders:
    pageSize: 10
  discount:
    codes:
      abcdef: 10

---
spring:
  profiles: prod

logging:
  level:
    tacos: WARN
